version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 3
    target-branch: dev
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    reviewers:
      - victorpreston
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 2
    target-branch: dev
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    reviewers:
      - victorpreston
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 1
    target-branch: dev
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    reviewers:
      - victorpreston
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: terraform
    directory: /infrastructure
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 1
    target-branch: dev
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    reviewers:
      - victorpreston
    commit-message:
      prefix: "chore"
      include: "scope"
