export enum TenantErrorCode {
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_ALREADY_EXISTS = 'TENANT_ALREADY_EXISTS',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  INVALID_TENANT_DATA = 'INVALID_TENANT_DATA',
  DUPLICATE_SLUG = 'DUPLICATE_SLUG',
}
